### ISSUE TITLE
一个openid可以为几个人打卡？

### ISSUE THREAD

**Issue by LXA2** [lthero-big/YouthStudyAuto#3]
一个微信号获取的openid可以上传多个人的信息吗？一个openid做多次（每次上传不同的名字），后台会显示只有一个人还是多个人？

**Comment by lthero-big** [comment]
openid相当于身份证号，每个人唯一对应一个openid，所以一个openid只能为一个人打卡。要让多人打卡需要找到所有人的openid

**Comment by LXA2** [comment]
一个ID做多次，每次提交不同的名字，团管理员看到的统计数据会是几个人呢？我测试了一个ID做了几十次，但是我自己在"qcsh.h5yunan.com"看到的学习记录只有最近的10次。

**Comment by lthero-big** [comment]
我没测试过，但按理一个ID做多次，每次提交不同的名字，最终只会有ID的原始人才打卡成功，打卡是绑定ID，应该和提交的名字没关系。“团管理员看到的统计数据会是几个人呢”----这得看学校怎么统计，如果学校按姓名统计，那可能就可以用一个ID提交不同名字。
